config/routes.rb
ProjectTracker::Application.routes.draw do

  resources :invitations

  resources :comments

  resources :projects do
    resources :features do
      get :mark_accepted, :on => :member
    end
  end

  devise_for :users

  get 'home/user_signout'
  get '/users/sign_up', as: 'sign_up'
  root to: "projects#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :feature
  attr_accessible :description

  default_scope order('created_at ASC') 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  before_filter :find_feature

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @feature.comments.build(:description => params[:new_comment])
    @comment.user = current_user
    emails = @feature.project.find_all_users - [current_user.email]

    respond_to do |format|
      if @comment.save
        UserMailer.new_comment(emails, current_user.email, @feature.project.title).deliver
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json 
        format.js 
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
  def find_feature
    puts params
    @feature = Feature.find(params[:feature_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.description
  = comment.description
b.comment-by
  'By:
  = comment.user.try(:email)
  /= link_to 'Show', comment
  /= link_to 'Edit', edit_comment_path(comment)
  /= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

hr

app/views/comments/_form.html.slim
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :feature
    = f.text_field :feature
  .actions = f.submit 'Save'

app/views/comments/_index.html.slim
h3 Comments

.comment
  - comments.each do |comment|
    = render 'comments/comment', :comment => comment

br
b Add Comment
#add-comment
  = hidden_field_tag 'feature_id', feature.id
  = text_area_tag 'new_comment'
  .save-button
    button id='save-comment' Save

app/views/comments/create.js.slim
'$(".comment").append("#{ j render 'comment', :comment => @comment }")

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  tr
    th Description
    th User
    th Feature
    th
    th
    th

  - @comments.each do |comment|
    tr
      td = comment.description
      td = comment.user
      td = comment.feature
      td = link_to 'Show', comment
      td = link_to 'Edit', edit_comment_path(comment)
      td = link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Description:
  = @comment.description
p
  strong User:
  = @comment.user
p
  strong Feature:
  = @comment.feature

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path