config/routes.rb
ProjectTracker::Application.routes.draw do

  resources :invitations

  resources :comments

  resources :projects do
    resources :features do
      get :mark_accepted, :on => :member
    end
  end

  devise_for :users

  get 'home/user_signout'
  get '/users/sign_up', as: 'sign_up'
  root to: "projects#index"

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :project
  attr_accessible :email

  validates_uniqueness_of :email, :scope => :project_id
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  # POST /invitations
  # POST /invitations.json
  def create
    emails = params[:invites].gsub(/\s+/, "").split(',')
    project = Project.find(params[:project_id])
    emails.each do |email|
      user = User.where(:email => email).count == 1 ? true : false
      invitation = Invitation.new(:email => email)
      invitation.project = project
      project_title = project.try(:title)
      if invitation.save
        UserMailer.invitation_confirmation(email, current_user.email, project_title, user).deliver
      end
    end

    render :text => 'Invitation sent successfully.'

  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.slim
= form_for @invitation do |f|
  - if @invitation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@invitation.errors.count, "error")} prohibited this invitation from being saved:"
      ul
        - @invitation.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :project
    = f.text_field :project
  .actions = f.submit 'Save'

app/views/invitations/edit.html.slim
h1 Editing invitation

== render 'form'

= link_to 'Show', @invitation
'|
= link_to 'Back', invitations_path

app/views/invitations/index.html.slim
h1 Listing invitations

table
  tr
    th Email
    th Project
    th
    th
    th

  - @invitations.each do |invitation|
    tr
      td = invitation.email
      td = invitation.project
      td = link_to 'Show', invitation
      td = link_to 'Edit', edit_invitation_path(invitation)
      td = link_to 'Destroy', invitation, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Invitation', new_invitation_path

app/views/invitations/new.html.slim
h1 New invitation

== render 'form'

= link_to 'Back', invitations_path

app/views/invitations/show.html.slim
p#notice = notice

p
  strong Email:
  = @invitation.email
p
  strong Project:
  = @invitation.project

= link_to 'Edit', edit_invitation_path(@invitation)
'|
= link_to 'Back', invitations_path