config/routes.rb
ProjectTracker::Application.routes.draw do

  resources :invitations

  resources :comments

  resources :projects do
    resources :features do
      get :mark_accepted, :on => :member
    end
  end

  devise_for :users

  get 'home/user_signout'
  get '/users/sign_up', as: 'sign_up'
  root to: "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :title
  has_one :project_owner, :class_name => "User"
  has_many :invitations
  has_many :features

  def find_all_users
    emails = self.invitations.map(&:email) 
    emails << self.user.email
    emails
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_for @project, :html => {:class => 'form-horizontal'} do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field.control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title
  .field.control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, rows: '10'
  .actions.control-group
    .controls = f.submit 'Save', class: 'btn'

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
h1 My Projects

- if current_user.projects.size > 0 || current_user.role?(:admin)
  table.table.table-bordered
    tr
      th Title
      th Description
      th

    - @projects.each do |project|
      - if can? :read, project
        tr
          td 
            h4 = project.title
          td 
            = project.description
          td
            = link_to 'Show', project, :class => 'btn' if can? :read, project
            '&nbsp;
            = link_to 'Invite', "#", :class => "btn invite-btn", :data => { :project => project.id } if can? :update, project
            '&nbsp;
            = link_to 'Edit', edit_project_path(project), :class => "btn btn-primary" if can? :update, project
            '&nbsp;
            = link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger" if can? :destroy, project
- else
  h3 No Projects found 

br

= link_to 'New Project', new_project_path, :class => "btn"

hr

- tracking_projects = current_user.tracking_projects
- if tracking_projects.size > 0
  h1 My Tracking Projects
 
  table.table.table-bordered
    tr
      th Title
      th Description
      th

    - tracking_projects.each do |project|
      - if can? :read, project
        tr
          td
            h4 = project.title
          td
            = project.description
          td
            = link_to 'Show', project, :class => 'btn' if can? :read, project
            '&nbsp;
            = link_to 'Invite', "#", :class => "btn invite-btn", :data => { :project => project.id } if can? :update, project
            '&nbsp;
            = link_to 'Edit', edit_project_path(project), :class => "btn btn-primary" if can? :update, project
            '&nbsp;
            = link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger" if can? :destroy, project
  

app/views/projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.slim
- if can? :read, @project
  p#notice = notice

  h2.center-text
    = @project.title.capitalize
  pre
    p
      = @project.description
  p 
    'Invitations sent to: 
    b = @project.invitations.map(&:email).join(', ')

  .pull-right
    = link_to 'Edit', edit_project_path(@project), :class => 'btn btn-primary' if can? :update, @project
    '&nbsp;
    = link_to 'Back', projects_path, :class => 'btn'

  br

  - if can? :read, @project
    = render 'features/index', :project => @project