config/routes.rb
ProjectTracker::Application.routes.draw do

  resources :invitations

  resources :comments

  resources :projects do
    resources :features do
      get :mark_accepted, :on => :member
    end
  end

  devise_for :users

  get 'home/user_signout'
  get '/users/sign_up', as: 'sign_up'
  root to: "projects#index"

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  before_update :save_history

  belongs_to :user
  belongs_to :project
  attr_accessible :description, :title, :priority, :status
  has_many :comments
  has_many :feature_histories

  default_scope order("priority ASC, created_at ASC")

  def incomplete
    if status == "1"
      return false
    end
    return true
  end

  def not_accepted?
    if accepted == 'yes'
      return false
    end
    return true
  end

  def save_history
    feature_history = FeatureHistory.new()
    feature_history.feature_id = self.id
    feature_history.priority = self.priority_was
    feature_history.title = self.title_was
    feature_history.description = self.description_was
    feature_history.status = self.status_was
    feature_history.user_id = self.user_id_was
    feature_history.created_at = self.created_at_was
    feature_history.updated_at = self.updated_at_was
    feature_history.save
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  load_and_authorize_resource :project, except: [:mark_accepted]
  load_and_authorize_resource through: :project, except: [:mark_accepted]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature.user = current_user

    respond_to do |format|
      if @feature.save
        format.html { redirect_to [@project, @feature], notice: 'Feature was successfully created.' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to [@project, @feature], notice: 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :no_content }
    end
  end

  def mark_accepted
    @feature = Feature.find(params[:id])
    if current_user.role?(:admin) || current_user.tracking_projects.include?(@feature.project)
      @feature.accepted = "yes"
      @feature.save
    else
      render text: 'not good'
    end
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.slim
= form_for [@project, @feature], html: { class: 'form-horizontal'} do |f|
  - if @feature.errors.any?
    #error_explanation
      h2 = "#{pluralize(@feature.errors.count, "error")} prohibited this feature from being saved:"
      ul
        - @feature.errors.full_messages.each do |message|
          li = message

  .field.control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title
  .field.control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, rows: '10'
  .field.control-group
    .controls
      label.checkbox
        = f.check_box :status
        'Complete
  .field.control-group
    = f.label :priority, :class => 'control-label'
    .controls
      = f.select :priority, [['Mandatory',1],['Desirable',2],['Optional',3],['Future Enhancement',4]]
  .actions.control-group 
    .controls = f.submit 'Save', class: 'btn'

app/views/features/_index.html.slim
- if can? :read, @project.features.build
  - features = @project.features.reject(&:new_record?)
  h1 Listing features

  table.table.table-bordered
    tr
      th Title
      th Description
      th User
      th Priority
      th
    - feature_priority = ["Mandatory","Desirable","Optional","Future Enhancement"]
    - features.each do |feature|
      tr class="#{'success' if !feature.not_accepted? }"
        /="#{feature_priority[feature.priority-1] if feature.priority}"
        td = feature.title
        td = feature.description
        td = feature.user.try(:email)
        td = feature_priority[feature.priority-1]
        td
           - if not feature.accepted && feature.accepted == "yes" 
             = link_to 'Show', [@project, feature], class: 'btn' if can? :read, feature
             '&nbsp;
           - if feature.status && feature.status == "1" && feature.not_accepted? && ( current_user.tracking_projects.include?(feature.project) || current_user.role?(:admin))
             = link_to 'Accept', mark_accepted_project_feature_path(@project, feature), class: 'btn' , remote: true, :data => { :featureid => feature.id }
             '&nbsp;
           - if not feature.accepted && feature.accepted == "yes" 
             = link_to 'Edit', edit_project_feature_path(@project, feature), class: 'btn btn-primary' if can? :update, feature
             '&nbsp;
             = link_to 'Destroy', [@project, feature], :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger' if can? :destroy, feature

  br
  - if can? :create, @project.features.build
    = link_to 'New Feature', new_project_feature_path(@project), class: 'btn'

app/views/features/edit.html.slim
h1 Editing feature

== render 'form'

= link_to 'Show', [@project, @feature], class: 'btn'
'&nbsp;
= link_to 'Back', project_path(@project), class: 'btn'

app/views/features/index.html.slim
h1 Listing features

table
  tr
    th Title
    th Description
    th User
    th Project
    th
    th
    th

  - @features.each do |feature|
    tr
      td = feature.title
      td = feature.description
      td = feature.user
      td = feature.project
      td = link_to 'Show', feature
      td = link_to 'Edit', edit_feature_path(feature)
      td = link_to 'Destroy', feature, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Feature', new_feature_path

app/views/features/mark_accepted.js.slim
'$('a[data-featureid="#{@feature.id}"]').hide()

app/views/features/new.html.slim
h1 New feature

== render 'form'

= link_to 'Back', project_path(@project)

app/views/features/show.html.slim
- if can? :read, @project
  - feature_priority = ['Mandatory', 'Desirable', 'Optional', 'Future Enhancement']
  - feature_priority_class = ['text-error', 'text-warning', 'text-info', 'text-success']
  p#notice = notice

  h2
    = @feature.title
  pre
    p
      = @feature.description
  p
    'Priority:
    b class="#{feature_priority_class[@feature.priority-1]}"
      = feature_priority[@feature.priority-1]
  p
    'Requested By:
    b
      = @feature.user.try(:email)
  p
    'Project :
    b
      = link_to @feature.project.try(:title), project_path(@project)

  .pull-right
    = link_to 'Edit', edit_project_feature_path(@project, @feature), class: 'btn' if can? :update, @feature
    '&nbsp;
    = link_to 'Back', project_path(@project), class: 'btn'

  br

  - if @feature.feature_histories.count > 0
    h4 History :
    .tabbable.tabs-left
      ul.nav.nav-tabs
        - @feature.feature_histories.each_with_index do |history, i|
          li class="#{'active' if i == 0 }"
            a data-toggle="tab" href="#history-#{history.id}" 
              = "Version #{i+1}"
      ul.tab-content
        - @feature.feature_histories.each_with_index do |history, i|
          div id="history-#{history.id}" class="tab-pane #{'active' if i == 0}"
            p = "Title : #{history.title}"
            p = "Description : #{history.description}"
            p = "Priority : #{feature_priority[history.priority-1]}"
            p = "Status : #{history.status && history.status == "1" ? 'Complete' : 'Incomplete' }"
            p = "By : #{history.user.try(:email)}"
            p = "At : #{history.updated_at.strftime("%Y-%m-%d %H:%M:%S UTC")}"

  br
  - if can? :read, @feature
    = render 'comments/index', :feature => @feature, :comments => @feature.comments